name: Renovate

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v42.0.3
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: "renovate.json"
        env:
          LOG_LEVEL: debug
          # RENOVATE_EXTRA_FLAGS: "--dry-run"